# frozen_string_literal: true

source "https://rubygems.org"

#git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'sinatra'
gem 'twitter'
gem 'pry'
gem 'shotgun' # Constantly reread the controller on every requests
